"""initial migration

Revision ID: 3dae387ad155
Revises: 
Create Date: 2018-09-03 13:35:30.099097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dae387ad155'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('child_id', postgresql.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_index(op.f('ix_child_created_at'), 'child', ['created_at'], unique=False)
    op.create_table('user_account',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_user_account_created_at'), 'user_account', ['created_at'], unique=False)
    op.create_table('event',
    sa.Column('event_id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('child_id', postgresql.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_child_id'), 'event', ['child_id'], unique=False)
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_started_at'), 'event', ['started_at'], unique=False)
    op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)
    op.create_table('user_child',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('child_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'child_id')
    )
    op.create_index('ix_user_child_child_id_user_id', 'user_child', ['child_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_child_child_id_user_id', table_name='user_child')
    op.drop_table('user_child')
    op.drop_index(op.f('ix_event_user_id'), table_name='event')
    op.drop_index(op.f('ix_event_started_at'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_index(op.f('ix_event_child_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_user_account_created_at'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_child_created_at'), table_name='child')
    op.drop_table('child')
    # ### end Alembic commands ###
