"""empty message

Revision ID: 64b4a145f638
Revises: 772586fb666b
Create Date: 2018-10-01 22:37:01.386721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b4a145f638'
down_revision = '772586fb666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('type', sa.String(), nullable=False))
    op.add_column('event', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'unit')
    op.drop_column('event', 'type')
    op.drop_column('event', 'amount')
    # ### end Alembic commands ###
