"""empty message

Revision ID: e64245435f46
Revises: 64b4a145f638
Create Date: 2018-10-04 00:14:45.895474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64245435f46'
down_revision = '64b4a145f638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('side', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'side')
    # ### end Alembic commands ###
